ORDapp/urls.py
from django.conf.urls import patterns, url
from ORDapp import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
)

SocialORD/urls.py
from django.conf.urls import patterns, include, url

from django_facebook import connect
from ORDapp import views
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', include('ORDapp.urls')),
	url(r'^login/$', views.login, name='login'),
	url(r'^register/$', views.register, name='register'),
	url(r'^reset/$', views.reset, name='reset'),
	url(r'^spectator_register/$', views.spectator_register, name='spectator_register'),
	url(r'^refresh_friends/$', views.refresh_friends, name='refresh_friends'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^facebook/', include('django_facebook.urls')),
	url(r'^accounts/', include('django_facebook.auth_urls')), #Don't add this line if you use django registration or userena for registration and auth.
)

ORDapp/models.py
from django.db import models
from django_facebook.models import FacebookCustomUser
from django.forms import ModelForm, DateField


class UserData(models.Model):
	Serving = models.BooleanField()
	Enhanced = models.BooleanField(blank=True)

	ORDDate = models.DateField(blank=True, null=True)
	user = models.OneToOneField(FacebookCustomUser, related_name='orddata')
	def __str__(self):
		return str(self.user)

class UserDataForm(ModelForm):
	class Meta:
		model = UserData
		fields = ['Serving','Enhanced','ORDDate']

ORDapp/views.py
from django.shortcuts import render
from open_facebook.api import OpenFacebook
from django.http import HttpResponseRedirect, HttpResponse
from django.db import models 
from django.dispatch.dispatcher import receiver 
from django_facebook.models import FacebookModel, FacebookProfile, BaseFacebookModel, FacebookCustomUser, FacebookUser
from django.db.models.signals import post_save 
from django_facebook.utils import get_user_model, get_profile_model 
from SocialORD import settings
from ORDapp.models import UserData,UserDataForm
from django.db.models import get_app, get_models, Count
from django.template import RequestContext, loader
from django.contrib.auth.decorators import login_required
from django_facebook.api import FacebookUserConverter
from open_facebook.api import OpenFacebook
from dateutil.relativedelta import relativedelta
from datetime import date
from django_facebook.decorators import facebook_required_lazy, facebook_required
from django.contrib import messages
from django.core.urlresolvers import reverse
import json


# Create your views here.
# @facebook_required(scope='publish_stream')
@login_required(login_url='/login/')
def index(request):
	daystillord = "nil"
	daysofservice = "nil"
	current_user = request.user

	if hasattr(current_user, 'orddata'):
		userdata_exists=True
	else:
		userdata_exists=False

	graph=OpenFacebook(current_user.facebookprofile.access_token)
	# graph.set('me/feed', message='tesdsat', url='http://www.google.com')

	json_friends=graph.get('v1.0/me/friends')

	json_friends_ids=[x['id'] for x in json_friends['data']]
	# json_test=str(json_friends)

	# json_extract=json_friends

	# friend_dict=json.loads(json_friends)
	# friend_dict=json.loads(json_test)
	# json_test=str(friend_dict)


	if userdata_exists==True and current_user.orddata.Serving == True:
		if current_user.orddata.Enhanced == True:
			enlist_date = current_user.orddata.ORDDate - relativedelta(years=1,months=10)
		else:
			enlist_date = current_user.orddata.ORDDate - relativedelta(years=2)

	else:
		enlist_date = None




	friends = FacebookUser.objects.filter(user_id = current_user.facebookprofile.user.id)
	users = FacebookProfile.objects.all()


	#get friends who are users of the site
	mutuals_set = set()
	for friend in json_friends_ids:
		for user in users:
			if int(friend) == user.facebook_id:
				mutuals_set.add(user.pk)


	mutuals = FacebookProfile.objects.filter(pk__in=mutuals_set)

	#filter friends on app to friends on app who input an ORD date
	mutuals_serving_set = set()
	for mutual in mutuals:
		try:
			mutual.user.orddata.ORDDate
			mutuals_serving_set.add(mutual.pk)
		except:
			pass


	#days left till ORD
	try:
		deltatillord = current_user.orddata.ORDDate - date.today()
		daystillord = deltatillord.days
	except:
		daystillord = 0

	#total days soldier needs to serve NS
	try:
		deltaofservice = enlist_date - current_user.orddata.ORDDate
		daysofservice = deltaofservice.days
	except:
		daysofservice = 0
	
	#add self to friend table for comparison
	try:
		current_user.orddata.ORDDate
		mutuals_serving_set.add(current_user.facebookprofile.pk)
	except:
		pass
		
# refernce code #
#	 {% for mutual in mutuals_serving %}
#	 {% if mutual.user.orddata.ORDDate %}
#	{{ mutual.user.orddata.ORDDate }}
# refernce code #

	mutuals_serving = FacebookProfile.objects.filter(pk__in=mutuals_serving_set)

	mutuals_serving = mutuals_serving.order_by('user__orddata__ORDDate')

	context = {'mutuals': mutuals,'UserData':UserData,'current_user':current_user,'userdata_exists':userdata_exists,'UserDataForm':UserDataForm,'mutuals_serving':mutuals_serving,'enlist_date':enlist_date,'daystillord':daystillord,'daysofservice':daysofservice}
	return render(request, 'ORDapp/index.html', context)


def login(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/')
	else:
		return render(request, 'ORDapp/login.html')

def register(request):
	Serving = True
	# Enhanced = request.POST['Enhanced']
	Enhanced = request.POST.get('Enhanced', False)
	ORDDate = request.POST['ORDDate']
	current_user = request.user

	r = UserData(Enhanced=Enhanced,Serving=Serving,ORDDate=ORDDate,user=current_user)
	try:
		r.save()
		return HttpResponseRedirect('/')
	except:
		# return HttpResponse("An error occourred. sian")
		messages.error(request, 'Did you enter a date?')
		return HttpResponseRedirect(reverse('index'))

def spectator_register(request):
	
	current_user = request.user
	r = UserData(Enhanced=False,Serving=False,ORDDate=None,user=current_user)
	try:
		r.save()
		return HttpResponseRedirect('/')
	except Exception, e:
		return HttpResponse(str(e))

def reset(request):
	current_user = request.user
	r = current_user.orddata
	r.delete()

	return HttpResponseRedirect('/')

def refresh_friends(request):
	current_user = request.user
	try:
		FacebookUserConverter.get_and_store_friends(current_user)
		return HttpResponseRedirect('/')
	except Exception, e:
		return HttpResponse(str(e))

templates/ORDapp/index.html
{% load staticfiles %}
{% load static %}
{% load ORDapp_extras %}

<head>
	<meta name="viewport" content="width=505">

	<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>-->

	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
	
	<script type="text/javascript" src="{% static "js/jquery.countdown.js" %}"></script>
	<script type="text/javascript" src="{% static "js/modernizr.js" %}"></script>
	<link href='http://fonts.googleapis.com/css?family=Arvo|Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static "css/countdown.css" %}" type="text/css" charset="utf-8"> 	
	<link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css" charset="utf-8">
	<title>ORDloh</title>

	<meta property="og:title" content="ORDloh"/>
	<meta property="og:type" content="website"/>
	<meta property="og:url" content="http://www.ordloh.com"/>
	<meta property="og:image" content="http://www.ordloh.com/static/img/sar21-p.png"/>
	<meta property="og:site_name" content="ORDloh"/>
	
	<meta property="og:description"
	  content="See when you and your friends ORD!"/>


	<script type="text/javascript">
	var aDay = new Date("{{ current_user.orddata.ORDDate.isoformat }}");
	$(function () {
	// var aDay = new Date();
	// aDay = new Date(2015, 3 - 1, 3, 14, 00 ,0 ,0);
	
	
	$('#defaultCountdown').countdown({until: aDay, format:'d',    labels: ['', '', '', '', '', '', ''], labels1: ['', '', '', '', '', '', '']});
	$('#year').text(aDay.getFullYear());
	});
	var daystillord = {{ daystillord }};
	var daysofservice = {{ daysofservice }};
	var workingdays = 0;
	var weekday     = new Array(7);
	var today = new Date();
	weekday[0]="Sunday";
	weekday[1]="Monday";
	weekday[2]="Tuesday";
	weekday[3]="Wednesday";
	weekday[4]="Thursday";
	weekday[5]="Friday";
	weekday[6]="Saturday";

	while (today <= aDay) 
	{
	    var day = weekday[today.getDay()];
	    if(day != "Saturday" && day != "Sunday") 
	    {
	        workingdays++; 
	    }
	    // console.log(weekday[today.getDay()]);
	    today = new Date(today.getTime() + 86400000); 
	}
	// console.log(workingdays);
	restdays = daystillord - workingdays;
	// console.log(restdays);
	percentdone = (daystillord / daysofservice * 100) + 100;
	percentdone = Math.round(percentdone * 10) / 10


	if(percentdone<0)
	{
		percentdone="Nil";
	} else{
		percentdone = percentdone.toString();
		percentdone = percentdone.concat("%");
	}
	// console.log(percentdone);

	// calculate days till next public holiday
	// javascript's months are zero-based

	var holidays = [
	new Date(2014,7-1,28),  		// HRP
	new Date(2014,8-1,9),  			// ND
	new Date(2014,10-1,5),  		// HRH
	new Date(2014,10-1,22),  		// Deepavali
	new Date(2014,12-1,25),  		// Christmas
	new Date(2015,1-1,1)  			// New Year
	];



	today = new Date();
	today.setHours(0);
	today.setMinutes(0);
	today.setSeconds(0);
	today.setMilliseconds(0);

	var i = 0;
	while(holidays[i])
	{
		if (holidays[i] > today)
		{
			// console.log(holidays[i]);
			next_holiday = new Date();
			next_holiday = holidays[i];
			break;
		}
		else
		{
			i++;
		}
	}

	console.log("next hol  -  " + next_holiday);
	var timeDiff = Math.abs(next_holiday.getTime() - today.getTime());
	var diffDays = Math.ceil(timeDiff / (1000 * 3600 * 24));
	console.log("days till next hol  -  " + diffDays);
	</script>
	


	<script>

	$(document).ready(function () {
	if (!Modernizr.inputtypes.date) {
    // $('input[type=date]').datepicker({
    $('#id_ORDDate').datepicker({
        // Consistent format with the HTML5 picker
        dateFormat: 'yy-mm-dd'
    });
	}
	});

	</script>
</head>

{% if user.is_authenticated %}
<body>


<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=755636921135503&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


	<div class="page-wrapper">
		<div class="header">
			<div class="left-header-btn">ORDloh</div>
			<!-- <div class="right-header-btn"> --><a href="{% url 'auth_logout' %}?next={{ request.path|urlencode }}" class="header-button header-button-2">Logout</a><!-- </div> -->
			{% if userdata_exists == True %}<!-- <div class="right-header-btn"> --><a href="{% url 'reset' %}" class="header-button header-button-2">Re-enter Data</a><!-- </div> -->{% endif %}
		</div>
		<div class="welcome">

			<div class="welcome_message">Hey {{ current_user }}! </div>
		</div>

		{% if messages %} 
		{% for message in messages %} 
		<div class="error">Error! {{ message }}</div>
		{% endfor %} 
		{% endif %}

		{% if userdata_exists == False %}
		<div class="ord_form">
			<img src="{% static "img/sar21s.png" %}" height="140px;" class="sar21">
			<div class="ord_entry">
				<p class="ord-prompt">When do you ORD?</p>
				<form id="register" action="{% url 'register' %}" method="POST" style="display:inline;"> {% csrf_token %}

					<label>
						<span>I'm in the enhanced batch</span>
						{{ UserDataForm.Enhanced }}
					</label>
					<br>
					<label>
						<span >ORD: </span>
						<input id="id_ORDDate" name="ORDDate" type="date">
					</label>
					<br>


					
					<input class="submit header-button header-button-1"  type="submit" value="ORD!"  />
				</form>

				<form id="register" action="{% url 'spectator_register' %}" method="POST" style="display:inline;"> {% csrf_token %}
					<input class="reject-button" type="submit" value="I'm not in NS"  />
				</form>
			</div>
		</div>


		{% endif %}


		{% if current_user.orddata.ORDDate %}
		
		<div class="timer-box">
			<div class="timer-element n1">
				<table height="270px" width="310px">
					<tr height="200px"><td><div id="hero-number" class="hero-number"></div></td></tr>
					<tr><td>Days till next public holiday</td></tr>
				</table>
			</div>
			<div class="timer-element n2">
				<table height="270px" width="310px">
					<tr>
						<td colspan="2" height="120px" style="padding:0px;margin:0px;"><div style="padding:0px;margin:0px;font-size:100px;"> {{ daystillord }} </div></td>

					</tr>
					<tr>
						<td colspan="2" height="40px" style="vertical-align: top;"><div style="text-align:center;">Days to ORD</div></td>
					</tr>
					<tr>
						<td><div class="sub-hero-number" id="weekdays"></div></td>
						<td><div class="sub-hero-number" id="weekends"></div></td>
					</tr>
					<tr>
						<td>Weekdays</td>
						<td>Weekends</td>
					</tr>
				</table>

				
			</div>
			<div class="timer-element n3">
				<table height="270px" width="310px">
					<tr height="200px"><td><div id="hero-percent"></div></td></tr>
					<tr><td>Done</td></tr>
				</table>
			</div>
			
		</div>

		<div class="orddate">ORD - {{ current_user.orddata.ORDDate |date:"M d, Y" }}</div>
		{% endif %}
		
		<div class="friend-table-box">
			{% for mutual in mutuals_serving %}
			{% if mutual.user.orddata.ORDDate %}
			<div class="friend-card">
				<div class="friend-card-top">
					<div class="friend-card-index">{{ forloop.counter }}</div>
					<div class="friend-card-img"><img height="70px" src="http://graph.facebook.com/{{ mutual.facebook_id }}/picture?height=70&width=70"></div>

				<div style="display: table; width:290px; height: 70px; overflow: hidden;">
					<div style="display: table-cell; vertical-align: middle; padding:0px 15px;">
						<div class="friend-card-name-table">
						 <a href="http://www.facebook.com/{{ mutual.facebook_id }}">{{ mutual.facebook_name }}</a>
						</div>
					</div>
				</div>

					<!-- <div class="friend-card-name"></div> -->
				</div>
				<div class="friend-card-mid">
					<div class="friend-card-ORD">{{ mutual.user.orddata.ORDDate }}</div>
				</div>
				<div class="friend-card-bot">
					
					<div class="friend-card-percent"><div style="padding-top:4px;"> {{ mutual.user.orddata.ORDDate|percentuntil:mutual.user.orddata.Enhanced }}</div></div>
					
					<div class="friend-card-days-remain">
						<div style="padding-top:4px;text-align:center;">
						<span style="">{{ mutual.user.orddata.ORDDate|daysuntil }}</span>
						</div>
					</div>
				</div>	
			</div>
			{% endif %}
			{% endfor %}


			<div class="friend-card-promo">
				<p>Want to see more of your friends? Share this page with them!</p>
				<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.ordloh.com" data-hashtags="ORDloh">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
				<div class="fb-like" data-href="http://www.ordloh.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
			</div>

		</div>


		
	</div>
</body>

<script type="text/javascript">
	document.getElementById("weekdays").innerHTML = workingdays;
	document.getElementById("weekends").innerHTML = restdays;
	document.getElementById("hero-percent").innerHTML = percentdone;
	document.getElementById("hero-number").innerHTML = diffDays;
</script>

<!-- <a href="{% url 'auth_logout' %}?next={{ request.path|urlencode }}">logout</a><br /> -->


{% endif %}

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55978518-1', 'auto');
  ga('send', 'pageview');

</script>

templates/ORDapp/login.html
{% load staticfiles %}
{% load static %}
<head>
		<meta name="viewport" content="width=550">
		<link rel="stylesheet" href="{% static "css/login.css" %}" type="text/css" charset="utf-8">
		<link href='http://fonts.googleapis.com/css?family=Arvo|Roboto:400,300,100,500' rel='stylesheet' type='text/css'>

		<meta property="og:title" content="ORDloh"/>
	<meta property="og:type" content="website"/>
	<meta property="og:url" content="http://www.ordloh.com"/>
	<meta property="og:image" content="http://www.ordloh.com/static/img/sar21-p.png"/>
	<meta property="og:site_name" content="ORDloh"/>
	
	<meta property="og:description"
	  content="See when you and your friends ORD!"/>
</head>

<body>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=755636921135503&version=v2.0";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="center-box">
		<div class="logo">
			<div class="logo-text" style="float:left;">ORDloh</div>
			<div style="float:right"><img height="85px" src="{% static "img/sar21-p.png" %}"></div>
		</div>

		<form class="signup_form" action="{% url 'facebook_connect' %}" method="post">
				<h2>Track when you and your friends ORD. <br>And shove it in their faces.</h2>
				<br />
				{% csrf_token %}
				<input type="hidden" value="{{ request.path }}" name="next" />
				<input type="hidden" value="{{ request.path }}" name="register_next" />

				<!--
				use error next for a seperate error page
				<input type="hidden" value="/error/" name="error_next" />
				-->

				<div id="facebook_login_redirect">
						<input type="image" src="{{ STATIC_URL }}django_facebook/images/facebook_login.png" /><br />
				</div>

				<div class="secure"><img src="https://cdn1.iconfinder.com/data/icons/defaulticon/icons/png/256x256/padlock-closed.png" height="16px;">  We will never post to Facebook without your permission</div>
		</form>

		<div class="feature">
			<div class="feature-text">
				<div class="feature-title">
					See when your friends ORD.
				</div>
				<div class="feature-content">
					
				</div>
			</div>
			<div class="feature-img">
				<img width="400px" src="{% static "img/demo_card.png" %}">
			</div>
		</div>
		
		<div class="feature">
			<div class="feature-text">
				<div class="feature-title">
					See detailed info about your ORD.
				</div>
				<div class="feature-content">
					
				</div>
			</div>
			<div class="feature-img">
				<img width="400px" src="{% static "img/demo_panel.png" %}">
			</div>
		</div>
		<div style="padding:10px;"><a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.ordloh.com" data-hashtags="ORDloh">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
				<div class="fb-like" data-href="http://www.ordloh.com" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div></div>
</div>

<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-55978518-1', 'auto');
	ga('send', 'pageview');

</script>
</body>